spring:
  datasource:    
    #PostgreSQL配置 postgres
      url: jdbc:postgresql://127.0.0.1:5432/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5431/wmsp?currentSchema=tenant_demo001
#    username: postgres
#    password: postgre@wmsp-ut
#    driver-class-name: org.postgresql.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    
      
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    cloud-platform: kubernetes
    banner-mode: off 

server:
  shutdown: graceful # 優雅下線
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: info
    com.example.demo: debug

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*" # 'health, info, env, prometheus, metrics, httptrace, threaddump, heapdump, loggers'
  endpoint:
    shutdown:
      enabled: true # shutDown RestAPI, UAT 以上環境關閉
    health:
      show-details: always # 顯示詳細健康檢查, UAT 以上環境關閉
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full